### ISSUE TITLE
Disable auto creation of curly brackets in CSS

### ISSUE THREAD

**Issue by alexkooksa** [Wikunia/brackets-jQuinter#10]
Hello! 
Would be great if there was an option to disable auto creation of curly brackets in CSS after I chose selector to complete.
It's cool when I need to specify only one class. But when I want to specify multiple classes and complete each of them, I have curly brackets created automatically every time, and for instance, `.one .more` turns to this:

```
.one .more {

}{

}
```

Could you fix it, please?

Thank you very much for such a useful extension!

**Comment by Wikunia** [comment]
It would be cooler if this can be done automatically right?
Adding of a new class name or something like that should not add curly braces?

**Comment by alexkooksa** [comment]
Yes, that would be great!

**Comment by Wikunia** [comment]
Don't want to add a options menu so I will try it out. Didn't work with Brackets a long time. Might take a bit ;)

**Comment by Wikunia** [comment]
Would be nice if you can install it using the link https://github.com/Wikunia/brackets-jQuinter. 
If it works fine I will register the new version. Thanks for the idea and have a nice weekend!

**Comment by alexkooksa** [comment]
Works perfect! Just what I needed :) Thank you so much, Ole!
Have a nice weekend too!
