### ISSUE TITLE
add php hint as well

### ISSUE THREAD

**Issue by ShahinSorkh** [Wikunia/brackets-jQuinter#8]

**Comment by Wikunia** [comment]
Can you give me any example, pls?

**Comment by ShahinSorkh** [comment]
you have auto completion hints for html, css, js, jquery
it's so good if you add php too

**Comment by Wikunia** [comment]
This extension provides autocompletion in matters of ids and classes. Therefore there are hints when writing a class name or id in html, css, js (jquery). Normally I am not using any classes in my php backend. For this reason I would like to get a code example ;)
