### ISSUE TITLE
Suggestion box doesn't show up

### ISSUE THREAD

**Issue by Navid-Ivanian** [Wikunia/brackets-jQuinter#9]
Hi
I have just tested your plug-in.Whenever I enter `$('.classname')` and then I put `.` the suggestion box doesn't show up!!!
![screenshot from 2016-09-11 08-57-58](https://cloud.githubusercontent.com/assets/21077608/18415187/fcb9c350-77fd-11e6-8247-6982a6b80064.png)
Here's my DevTools Logs:
![screenshot from 2016-09-11 08-49-56](https://cloud.githubusercontent.com/assets/21077608/18415159/cf9d3b82-77fc-11e6-9375-4c9ae8f785ac.png)

**Comment by Wikunia** [comment]
Sry, that is not part of my extension. My extension shows hints of classes and ids but no general jquery functions.

**Comment by Navid-Ivanian** [comment]
Yeap,but I saw something in the demo of your extension!What are those?
If your extension doesn't do that is there any other plug-in for jquery???
I really need it :cry:

**Comment by Wikunia** [comment]
Which version of brackets do you use?
![brackets_hints](https://cloud.githubusercontent.com/assets/4931746/18417372/a56548be-782e-11e6-8700-067c4c9a502c.png)

This is my hint view in version 1.7 which is even better than the one in my demo ;)

**Comment by Navid-Ivanian** [comment]
@Wikunia I use brackets `Release 1.7 experimental build 1.7.0-16898 (release b0a363b71)`.
What's that extension???

**Comment by Wikunia** [comment]
There is no extension! I loaded brackets without extensions (using Debug - Reload without extensions)

**Comment by Navid-Ivanian** [comment]
@Wikunia Are you sure???!!! It doesn't work for me :confused:

**Comment by Wikunia** [comment]
Well I used the Reload without extensions function and it is mentioned here (second bullet point)
https://github.com/adobe/brackets/wiki/Release-Notes:-1.6
